#!/usr/bin/env bash
#
# Regenerate THIRD_PARTY_LICENSES: an aggregated attribution file covering every
# dependency that is actually redistributed inside docs-sign — both the Go modules
# compiled into the binary and the npm packages bundled into the embedded frontend.
#
# It deliberately scopes to what *ships*, not the full module/dev graph:
#   - Go:  modules reachable from `go list -deps ./cmd/docs-sign` (excludes test/tooling deps)
#   - npm: the production dependency closure under web/ (excludes devDependencies)
#
# Plus licenses/extra-notices.txt, which carries notices for embedded components whose
# license text is not present in the module cache (notably the PDFium WASM and the
# third-party libraries PDFium bundles).
#
# Run from the repo root (or via `make licenses`). Requires the Go module cache to be
# populated (`go mod download`) and web/node_modules installed (`npm ci`).

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

out="THIRD_PARTY_LICENSES"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

sep="================================================================================"

emit_file() {
    # emit_file <header> <path>
    local header="$1" path="$2"
    {
        printf '\n%s\n%s\n%s\n\n' "$sep" "$header" "$sep"
        if [ -n "$path" ] && [ -f "$path" ]; then
            cat "$path"
        else
            printf '(no license file shipped with this package)\n'
        fi
    } >>"$tmp"
}

{
    printf 'THIRD-PARTY SOFTWARE NOTICES AND LICENSES\n'
    printf '%s\n\n' "$sep"
    printf 'docs-sign redistributes the third-party components listed below, both within the\n'
    printf 'compiled binary and within the embedded web frontend. Their copyright notices and\n'
    printf 'license terms are reproduced here as required by those licenses. This file is\n'
    printf 'generated by scripts/gen-third-party-licenses.sh; do not edit it by hand.\n'
} >"$tmp"

# Curated notices for embedded components not covered by the module cache (PDFium, etc.).
if [ -f licenses/extra-notices.txt ]; then
    {
        printf '\n\n%s\n' "$sep"
        printf 'EMBEDDED NATIVE / WEBASSEMBLY COMPONENTS\n'
        printf '%s\n' "$sep"
    } >>"$tmp"
    cat licenses/extra-notices.txt >>"$tmp"
fi

# ---- Go modules compiled into ./cmd/docs-sign --------------------------------------
{
    printf '\n\n%s\n' "$sep"
    printf 'GO MODULES (compiled into the docs-sign binary)\n'
    printf '%s\n' "$sep"
} >>"$tmp"

# Path<TAB>Version<TAB>Dir for every non-stdlib dependency module reachable from the
# command. Requiring .Module.Version to be non-empty excludes the main module (docs-sign
# itself), which keeps every emitted line fully populated so tab fields don't collapse.
go list -deps -f '{{if and (not .Standard) .Module .Module.Version}}{{.Module.Path}}{{"\t"}}{{.Module.Version}}{{"\t"}}{{.Module.Dir}}{{end}}' ./cmd/docs-sign \
    | sort -u | while IFS=$'\t' read -r path version dir; do
    [ -n "$dir" ] && [ -d "$dir" ] || { emit_file "$path@$version" ""; continue; }
    files="$(find "$dir" -maxdepth 2 -type f \
        \( -iname 'LICENSE*' -o -iname 'COPYING*' -o -iname 'NOTICE*' -o -iname 'PATENTS*' \) \
        2>/dev/null | sort || true)"
    if [ -z "$files" ]; then
        emit_file "$path@$version" ""
        continue
    fi
    while IFS= read -r f; do
        emit_file "$path@$version  (${f#"$dir"/})" "$f"
    done <<<"$files"
done

# ---- npm production dependencies bundled into the frontend --------------------------
{
    printf '\n\n%s\n' "$sep"
    printf 'NPM PACKAGES (bundled into the embedded web frontend)\n'
    printf '%s\n' "$sep"
} >>"$tmp"

( cd web && npm ls --omit=dev --all --parseable 2>/dev/null ) \
    | sort -u | while IFS= read -r dir; do
    [ -d "$dir" ] || continue
    case "$dir" in */node_modules/*) : ;; *) continue ;; esac   # only real deps, not the web/ root
    pkgjson="$dir/package.json"
    [ -f "$pkgjson" ] || continue
    meta="$(python3 - "$pkgjson" <<'PY'
import json, sys
p = json.load(open(sys.argv[1]))
lic = p.get("license") or ""
if not lic and isinstance(p.get("licenses"), list):
    lic = ",".join(x.get("type", "") for x in p["licenses"])
print(f"{p.get('name','?')}@{p.get('version','?')}\t{lic}")
PY
)"
    name_ver="${meta%%$'\t'*}"
    lic="${meta#*$'\t'}"
    file="$(find "$dir" -maxdepth 1 -type f \
        \( -iname 'LICENSE*' -o -iname 'COPYING*' -o -iname 'NOTICE*' \) \
        2>/dev/null | sort | head -1)"
    emit_file "$name_ver  (SPDX: ${lic:-unknown})" "$file"
done

mv "$tmp" "$out"
trap - EXIT
echo "wrote $out ($(wc -l <"$out") lines)"
